version: "3.7"

services:
  fingerprinter-api:
    container_name: fingerprinter-api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${FINGERPRINTER_API_PORT}:${FINGERPRINTER_API_PORT}
    env_file: docker/.env
    networks:
      - mydefault

  fingerprinter-ui:
    container_name: fingerprinter-ui
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${FINGERPRINTER_UI_PORT}:${FINGERPRINTER_UI_PORT}
    env_file: docker/.env
    depends_on:
      - "fingerprinter-api"
    networks:
      - mydefault

  fuseki:
    container_name: fuseki
    build:
      context: .
      dockerfile: docker/fuseki/Dockerfile
    volumes:
      - ${PWD}/${FUSEKI_DATA_FOLDER}/fuseki:/fuseki
    env_file: docker/.env
    environment:
      - ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${FUSEKI_JVM_ARGS}
    ports:
      - ${FUSEKI_PORT}:${FUSEKI_PORT}
    networks:
      - mydefault

networks:
  mydefault:
    name: globalnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24