openapi: 3.0.1

info:
  title: Fingerprinting Service
  description: |
    This API provides the possibility to fingerprint an RDF file or SPARQL endpoint.

  contact:
    name: Eugeniu Costetchi
    url: http://costezki.ro
    email: costezki.eugen@gmail.com
  license:
    name: GNU General Public License Version 3 (GPLv3)
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.1

servers:
  - url: 'http://localhost:4020/'
    description: Default server

components:
  parameters:
    extensionParam:
      in: query
      name: report_type
      required: false
      schema:
        type: string
      description: The type of the report that will be returned

  schemas:
    BaseFingerprinter:
      type: object
      description: Base fingerprinter schema to be used by the endpoint and file fingerprinter
      properties:
        graph:
          type: string
          description: A named graph to restrict the fingerprint calculation to

    EndpointFingerprinter:
      type: object
      description: Fingerprint a SPARQL endpoint
      allOf:
        - $ref: '#components/schemas/BaseFingerprinter'
        - type: object
          properties:
            sparql_endpoint_url:
              type: string
              description: The endpoint to validate
          required:
            - sparql_endpoint_url

    FileFingerprinter:
      type: object
      description: Fingerprint a file
      allOf:
        - $ref: '#components/schemas/BaseFingerprinter'
        - type: object
          properties:
            data_file:
              type: string
              format: binary
              description: The file to be fingerprinted
          required:
            - data_file

paths:
  /fingerprint-sparql-endpoint:
    post:
      operationId: fingerprinter.entrypoints.api.handlers.fingerprint_sparql_endpoint
      description: Fingerprint a SPARQL endpoint.
      parameters:
        - $ref: '#/components/parameters/extensionParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointFingerprinter'
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.
  /fingerprint-file:
    post:
      operationId: fingerprinter.entrypoints.api.handlers.fingerprint_file
      description: Fingerprint an RDF file.
      parameters:
        - $ref: '#/components/parameters/extensionParam'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/FileFingerprinter'
      responses:
        200:
          description: OK.
        5XX:
          description: Unexpected Error.
